/// Node kind enum — type-safe representation of AST node kinds.

/// All possible node kinds stored in kerai.nodes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Kind {
    // Top-level
    Crate,
    Module,
    File,

    // Items
    Fn,
    Struct,
    Enum,
    Variant,
    Field,
    Impl,
    Trait,
    TypeAlias,
    Const,
    Static,
    Use,
    ExternCrate,
    ForeignMod,
    Union,
    TraitAlias,

    // Macros
    MacroDef,
    MacroCall,

    // Attributes and comments
    Attribute,
    DocComment,
    Comment,
    CommentBlock,

    // Blocks and statements
    Block,
    StmtLocal,
    StmtExpr,

    // Expressions
    ExprCall,
    ExprMethodCall,
    ExprIf,
    ExprMatch,
    ExprMatchArm,
    ExprClosure,
    ExprBlock,
    ExprLoop,
    ExprWhile,
    ExprFor,
    ExprReturn,
    ExprBreak,
    ExprContinue,
    ExprAssign,
    ExprBinary,
    ExprUnary,
    ExprField,
    ExprIndex,
    ExprReference,
    ExprStruct,
    ExprTuple,
    ExprArray,
    ExprCast,
    ExprPath,
    ExprRange,
    ExprLet,
    ExprAsync,
    ExprAwait,
    ExprTry,
    ExprYield,
    ExprUnsafe,
    ExprConst,
    ExprRepeat,
    ExprParen,
    ExprOther,

    // Patterns
    PatIdent,
    PatStruct,
    PatTupleStruct,
    PatTuple,
    PatOr,
    PatSlice,
    PatRest,
    PatWild,
    PatRange,
    PatRef,
    PatLit,
    PatPath,
    PatOther,

    // Leaves
    Ident,
    Lit,
    Lifetime,
    GenericParam,

    // Cargo
    CargoToml,
    Dependency,

    // Type nodes
    TypePath,
    TypeReference,
    TypeTuple,
    TypeArray,
    TypeSlice,
    TypeFn,
    TypeImplTrait,
    TypeDynTrait,
    TypeNever,
    TypeInfer,
    TypeOther,

    // Function signature parts
    Param,
    ReturnType,

    // Catch-all "other" variants for item types
    ItemOther,
    ImplItemOther,
    TraitItemOther,
}

impl Kind {
    /// The SQL/storage string value for this kind.
    pub fn as_str(&self) -> &'static str {
        match self {
            // Top-level
            Kind::Crate => "crate",
            Kind::Module => "module",
            Kind::File => "file",
            // Items
            Kind::Fn => "fn",
            Kind::Struct => "struct",
            Kind::Enum => "enum",
            Kind::Variant => "variant",
            Kind::Field => "field",
            Kind::Impl => "impl",
            Kind::Trait => "trait",
            Kind::TypeAlias => "type_alias",
            Kind::Const => "const",
            Kind::Static => "static",
            Kind::Use => "use",
            Kind::ExternCrate => "extern_crate",
            Kind::ForeignMod => "foreign_mod",
            Kind::Union => "union",
            Kind::TraitAlias => "trait_alias",
            // Macros
            Kind::MacroDef => "macro_def",
            Kind::MacroCall => "macro_call",
            // Attributes and comments
            Kind::Attribute => "attribute",
            Kind::DocComment => "doc_comment",
            Kind::Comment => "comment",
            Kind::CommentBlock => "comment_block",
            // Blocks and statements
            Kind::Block => "block",
            Kind::StmtLocal => "stmt_local",
            Kind::StmtExpr => "stmt_expr",
            // Expressions
            Kind::ExprCall => "expr_call",
            Kind::ExprMethodCall => "expr_method_call",
            Kind::ExprIf => "expr_if",
            Kind::ExprMatch => "expr_match",
            Kind::ExprMatchArm => "expr_match_arm",
            Kind::ExprClosure => "expr_closure",
            Kind::ExprBlock => "expr_block",
            Kind::ExprLoop => "expr_loop",
            Kind::ExprWhile => "expr_while",
            Kind::ExprFor => "expr_for",
            Kind::ExprReturn => "expr_return",
            Kind::ExprBreak => "expr_break",
            Kind::ExprContinue => "expr_continue",
            Kind::ExprAssign => "expr_assign",
            Kind::ExprBinary => "expr_binary",
            Kind::ExprUnary => "expr_unary",
            Kind::ExprField => "expr_field",
            Kind::ExprIndex => "expr_index",
            Kind::ExprReference => "expr_reference",
            Kind::ExprStruct => "expr_struct",
            Kind::ExprTuple => "expr_tuple",
            Kind::ExprArray => "expr_array",
            Kind::ExprCast => "expr_cast",
            Kind::ExprPath => "expr_path",
            Kind::ExprRange => "expr_range",
            Kind::ExprLet => "expr_let",
            Kind::ExprAsync => "expr_async",
            Kind::ExprAwait => "expr_await",
            Kind::ExprTry => "expr_try",
            Kind::ExprYield => "expr_yield",
            Kind::ExprUnsafe => "expr_unsafe",
            Kind::ExprConst => "expr_const",
            Kind::ExprRepeat => "expr_repeat",
            Kind::ExprParen => "expr_paren",
            Kind::ExprOther => "expr_other",
            // Patterns
            Kind::PatIdent => "pat_ident",
            Kind::PatStruct => "pat_struct",
            Kind::PatTupleStruct => "pat_tuple_struct",
            Kind::PatTuple => "pat_tuple",
            Kind::PatOr => "pat_or",
            Kind::PatSlice => "pat_slice",
            Kind::PatRest => "pat_rest",
            Kind::PatWild => "pat_wild",
            Kind::PatRange => "pat_range",
            Kind::PatRef => "pat_ref",
            Kind::PatLit => "pat_lit",
            Kind::PatPath => "pat_path",
            Kind::PatOther => "pat_other",
            // Leaves
            Kind::Ident => "ident",
            Kind::Lit => "lit",
            Kind::Lifetime => "lifetime",
            Kind::GenericParam => "generic_param",
            // Cargo
            Kind::CargoToml => "cargo_toml",
            Kind::Dependency => "dependency",
            // Types
            Kind::TypePath => "type_path",
            Kind::TypeReference => "type_reference",
            Kind::TypeTuple => "type_tuple",
            Kind::TypeArray => "type_array",
            Kind::TypeSlice => "type_slice",
            Kind::TypeFn => "type_fn",
            Kind::TypeImplTrait => "type_impl_trait",
            Kind::TypeDynTrait => "type_dyn_trait",
            Kind::TypeNever => "type_never",
            Kind::TypeInfer => "type_infer",
            Kind::TypeOther => "type_other",
            // Function signature
            Kind::Param => "param",
            Kind::ReturnType => "return_type",
            // Catch-all others
            Kind::ItemOther => "item_other",
            Kind::ImplItemOther => "impl_item_other",
            Kind::TraitItemOther => "trait_item_other",
        }
    }

    /// All Kind variants, for exhaustive iteration and testing.
    pub const ALL: &'static [Kind] = &[
        Kind::Crate, Kind::Module, Kind::File,
        Kind::Fn, Kind::Struct, Kind::Enum, Kind::Variant, Kind::Field,
        Kind::Impl, Kind::Trait, Kind::TypeAlias, Kind::Const, Kind::Static,
        Kind::Use, Kind::ExternCrate, Kind::ForeignMod, Kind::Union, Kind::TraitAlias,
        Kind::MacroDef, Kind::MacroCall,
        Kind::Attribute, Kind::DocComment, Kind::Comment, Kind::CommentBlock,
        Kind::Block, Kind::StmtLocal, Kind::StmtExpr,
        Kind::ExprCall, Kind::ExprMethodCall, Kind::ExprIf, Kind::ExprMatch,
        Kind::ExprMatchArm, Kind::ExprClosure, Kind::ExprBlock, Kind::ExprLoop,
        Kind::ExprWhile, Kind::ExprFor, Kind::ExprReturn, Kind::ExprBreak,
        Kind::ExprContinue, Kind::ExprAssign, Kind::ExprBinary, Kind::ExprUnary,
        Kind::ExprField, Kind::ExprIndex, Kind::ExprReference, Kind::ExprStruct,
        Kind::ExprTuple, Kind::ExprArray, Kind::ExprCast, Kind::ExprPath,
        Kind::ExprRange, Kind::ExprLet, Kind::ExprAsync, Kind::ExprAwait,
        Kind::ExprTry, Kind::ExprYield, Kind::ExprUnsafe, Kind::ExprConst,
        Kind::ExprRepeat, Kind::ExprParen, Kind::ExprOther,
        Kind::PatIdent, Kind::PatStruct, Kind::PatTupleStruct, Kind::PatTuple,
        Kind::PatOr, Kind::PatSlice, Kind::PatRest, Kind::PatWild, Kind::PatRange,
        Kind::PatRef, Kind::PatLit, Kind::PatPath, Kind::PatOther,
        Kind::Ident, Kind::Lit, Kind::Lifetime, Kind::GenericParam,
        Kind::CargoToml, Kind::Dependency,
        Kind::TypePath, Kind::TypeReference, Kind::TypeTuple, Kind::TypeArray,
        Kind::TypeSlice, Kind::TypeFn, Kind::TypeImplTrait, Kind::TypeDynTrait,
        Kind::TypeNever, Kind::TypeInfer, Kind::TypeOther,
        Kind::Param, Kind::ReturnType,
        Kind::ItemOther, Kind::ImplItemOther, Kind::TraitItemOther,
    ];
}

impl std::fmt::Display for Kind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::str::FromStr for Kind {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "crate" => Ok(Kind::Crate),
            "module" => Ok(Kind::Module),
            "file" => Ok(Kind::File),
            "fn" => Ok(Kind::Fn),
            "struct" => Ok(Kind::Struct),
            "enum" => Ok(Kind::Enum),
            "variant" => Ok(Kind::Variant),
            "field" => Ok(Kind::Field),
            "impl" => Ok(Kind::Impl),
            "trait" => Ok(Kind::Trait),
            "type_alias" => Ok(Kind::TypeAlias),
            "const" => Ok(Kind::Const),
            "static" => Ok(Kind::Static),
            "use" => Ok(Kind::Use),
            "extern_crate" => Ok(Kind::ExternCrate),
            "foreign_mod" => Ok(Kind::ForeignMod),
            "union" => Ok(Kind::Union),
            "trait_alias" => Ok(Kind::TraitAlias),
            "macro_def" => Ok(Kind::MacroDef),
            "macro_call" => Ok(Kind::MacroCall),
            "attribute" => Ok(Kind::Attribute),
            "doc_comment" => Ok(Kind::DocComment),
            "comment" => Ok(Kind::Comment),
            "comment_block" => Ok(Kind::CommentBlock),
            "block" => Ok(Kind::Block),
            "stmt_local" => Ok(Kind::StmtLocal),
            "stmt_expr" => Ok(Kind::StmtExpr),
            "expr_call" => Ok(Kind::ExprCall),
            "expr_method_call" => Ok(Kind::ExprMethodCall),
            "expr_if" => Ok(Kind::ExprIf),
            "expr_match" => Ok(Kind::ExprMatch),
            "expr_match_arm" => Ok(Kind::ExprMatchArm),
            "expr_closure" => Ok(Kind::ExprClosure),
            "expr_block" => Ok(Kind::ExprBlock),
            "expr_loop" => Ok(Kind::ExprLoop),
            "expr_while" => Ok(Kind::ExprWhile),
            "expr_for" => Ok(Kind::ExprFor),
            "expr_return" => Ok(Kind::ExprReturn),
            "expr_break" => Ok(Kind::ExprBreak),
            "expr_continue" => Ok(Kind::ExprContinue),
            "expr_assign" => Ok(Kind::ExprAssign),
            "expr_binary" => Ok(Kind::ExprBinary),
            "expr_unary" => Ok(Kind::ExprUnary),
            "expr_field" => Ok(Kind::ExprField),
            "expr_index" => Ok(Kind::ExprIndex),
            "expr_reference" => Ok(Kind::ExprReference),
            "expr_struct" => Ok(Kind::ExprStruct),
            "expr_tuple" => Ok(Kind::ExprTuple),
            "expr_array" => Ok(Kind::ExprArray),
            "expr_cast" => Ok(Kind::ExprCast),
            "expr_path" => Ok(Kind::ExprPath),
            "expr_range" => Ok(Kind::ExprRange),
            "expr_let" => Ok(Kind::ExprLet),
            "expr_async" => Ok(Kind::ExprAsync),
            "expr_await" => Ok(Kind::ExprAwait),
            "expr_try" => Ok(Kind::ExprTry),
            "expr_yield" => Ok(Kind::ExprYield),
            "expr_unsafe" => Ok(Kind::ExprUnsafe),
            "expr_const" => Ok(Kind::ExprConst),
            "expr_repeat" => Ok(Kind::ExprRepeat),
            "expr_paren" => Ok(Kind::ExprParen),
            "expr_other" => Ok(Kind::ExprOther),
            "pat_ident" => Ok(Kind::PatIdent),
            "pat_struct" => Ok(Kind::PatStruct),
            "pat_tuple_struct" => Ok(Kind::PatTupleStruct),
            "pat_tuple" => Ok(Kind::PatTuple),
            "pat_or" => Ok(Kind::PatOr),
            "pat_slice" => Ok(Kind::PatSlice),
            "pat_rest" => Ok(Kind::PatRest),
            "pat_wild" => Ok(Kind::PatWild),
            "pat_range" => Ok(Kind::PatRange),
            "pat_ref" => Ok(Kind::PatRef),
            "pat_lit" => Ok(Kind::PatLit),
            "pat_path" => Ok(Kind::PatPath),
            "pat_other" => Ok(Kind::PatOther),
            "ident" => Ok(Kind::Ident),
            "lit" => Ok(Kind::Lit),
            "lifetime" => Ok(Kind::Lifetime),
            "generic_param" => Ok(Kind::GenericParam),
            "cargo_toml" => Ok(Kind::CargoToml),
            "dependency" => Ok(Kind::Dependency),
            "type_path" => Ok(Kind::TypePath),
            "type_reference" => Ok(Kind::TypeReference),
            "type_tuple" => Ok(Kind::TypeTuple),
            "type_array" => Ok(Kind::TypeArray),
            "type_slice" => Ok(Kind::TypeSlice),
            "type_fn" => Ok(Kind::TypeFn),
            "type_impl_trait" => Ok(Kind::TypeImplTrait),
            "type_dyn_trait" => Ok(Kind::TypeDynTrait),
            "type_never" => Ok(Kind::TypeNever),
            "type_infer" => Ok(Kind::TypeInfer),
            "type_other" => Ok(Kind::TypeOther),
            "param" => Ok(Kind::Param),
            "return_type" => Ok(Kind::ReturnType),
            "item_other" => Ok(Kind::ItemOther),
            "impl_item_other" => Ok(Kind::ImplItemOther),
            "trait_item_other" => Ok(Kind::TraitItemOther),
            other => Err(format!("unknown kind: {}", other)),
        }
    }
}

